version: '3'
services:
  db:
    image: postgres:12.6-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tasker_repo
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
    - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080
    links:
    - db

  server:
    build: .
    ports:
      - "80:80"
    links:
      - db
    depends_on:
      - db

volumes:
  pgdata:
    external: true
