version: '3'
services:
  db:
    image: postgis/postgis
    restart: always
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    volumes:
    - pgdata:/var/lib/postgresql/data
    ports:
    - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080
    links:
    - db

  # server:
  #   image: tasker:latest
  #   build:
  #     context: .
  #   depends_on:
  #     - db
  #   links:
  #   - db
    # environment:
    # - PGHOST: db
    # - PGDATABASE: postgres
    # - PGUSER: postgres
    # - PGPASSWORD: postgres

volumes:
  pgdata:
    external: true
