version: '3'
services:
  db:
    image: postgres:12.6-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tasker_repo
      # - POSTGRES_DB=tasker_repo_dev
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
    - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
    - 8080:8080
    links:
    - db
    logging:
      options:
        max-size: 1m

  server:
    build: .
    ports:
      - "11697:80"
    links:
      - db
    depends_on:
      - db

  tasker:
    image: istudyatuni/tasker:latest
    ports:
      - "11697:80"
    links:
      - db
    depends_on:
      - db

volumes:
  pgdata:
    external: true
