name: Build and deploy
on:
  push:
    branches:
      - master
    paths:
      - 'web/**'
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Build
        run: |
          cp docs/tasker-data-example.json web/public
          cd web
          yarn install --frozen-lockfile
          yarn build
          touch build/.nojekyll
          echo $GITHUB_SHA > build/version.txt

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: web/build
          single-commit: true
